# Service Registry Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.206.125.179:8761/eureka/
  instance:
    hostname: 15.206.125.179
