# Service Registry Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.204.232.113:80/eureka/
  instance:
    hostname: 43.204.232.113
